version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install and build dependencies in both apps
      - run:
          name: install dependencies in client
          command: |
            npm cache clean -f && rm -rf node_modules && npm i --prefix ./complete
      - run:
          name: install dependencies in server
          command: |
            npm cache clean -f && rm -rf node_modules && npm i --prefix ./server
      - run:
          name: build client
          command: |
            npm run build --prefix ./complete
      - run:
          name: build server
          command: |
            npm run build --prefix ./server
