version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install and build dependencies in both apps
      - run:
          name: install dependencies in client
          command: |
            npm complete:install
      - run:
          name: install dependencies in server
          command: |
            npm server:install
      - run:
          name: build client
          command: |
            npm run complete:build
      - run:
          name: build server
          command: |
            npm run server:build
